### ISSUE TITLE
ServiceLoader is very, very expensive on Android, please just crash instead

### ISSUE THREAD

**Issue by LouisCAD** [whyoleg/sweet-spi#1]
Hi, if you dig into kotlinx.coroutines issues about ServiceLoader, you will see it's unfortunately very expensive on Android. Probably best to stick to build-time only behavior, or implement a custom, cheaper and R8 safe way to do what ServiceLoader does.

**Comment by whyoleg** [comment]
Hey! yeah, that's unfortunate and would be nice to have. As far as I understand, R8 can transform specific calls in a form of:
`ServiceLoader.load(X.class, X.class.getClassLoader()).iterator()` ([source](https://r8.googlesource.com/r8/+/refs/heads/main/src/main/java/com/android/tools/r8/ir/optimize/ServiceLoaderRewriter.java))
So probably it's doable. Would be nice to hear on how to better test it.

**Comment by whyoleg** [comment]
FYI, I was able to test and fix the performance of `ServiceLoader` on Android.
I don't have real device at my side, but I do believe that there should be no difference
